### ISSUE TITLE
How can I use other data sources to overlay?

### ISSUE THREAD

**Issue by dementiev** [mapbox/martini#17]
Hi, 
I want to overlay 3d elevation model with other datasources (we have our own wms/wfs server with vector and raster layers). Is that possiible to do that? 

Thanks!

**Comment by kylebarron** [comment]
`martini` and `delatin` just create a mesh. Combining with raster images is out of scope for the projects. You can use other projects like Cesium or deck.gl ([example](https://deck.gl/examples/terrain-layer/)) to render the mesh.

**Comment by dementiev** [comment]
Thank you for the answer!
