### ISSUE TITLE
Not on NPM yet?

### ISSUE THREAD

**Issue by gpbmike** [mapbox/martini#2]
Hi, I see `npm install @mapbox/martini` on the README but I don't see the package on NPM. Perhaps it's set to private?

This is where I'm looking: https://www.npmjs.com/package/@mapbox/martini

Thanks.

**Comment by gpbmike** [comment]
Really cool work by the way. I'm doing something similar but way slower and wanted to try your approach. 🙏

**Comment by mourner** [comment]
Oh, yeah, didn't publish yet — will do that now.

**Comment by mourner** [comment]
Published now!
