### ISSUE TITLE
Can we add support for interaction?

### ISSUE THREAD

**Issue by EverWinter23** [mapbox/martini#3]
Elevation value of a point on hover, elevation profile of a line.

How would one go about it?-- if it can be achieved. Could restricting the model to 2d while interacting help, or can we achieve the same in 3d.

Thanks. Martini is :fire:  :fire: 

**Edit 1:** CDN support would be really appreciated for quick prototyping.

**Edit 2:** `terrain` has to be calculated by the user rather than the library, but certain front-end frameworks don't give you access to the DOM-- like `Vue`

**Comment by mourner** [comment]
Interaction is out of scope for this library. It's focused strictly on an algorithm for generating a mesh.
