### ISSUE TITLE
Bundled/Minified file still named `martin.js`

### ISSUE THREAD

**Issue by kylebarron** [mapbox/martini#8]
Awesome library; I love your work! When installed from NPM, there's the main `index.js` file and also bundled `martin.js` and `martin.min.js`. It looks like the rollup config is still set to those names:
https://github.com/mapbox/martini/blob/f87ad03edae1d42cd0cc773ac794e3f41c01d778/rollup.config.js#L15-L16

Did you mean to rename those to Martini too?

**Comment by mootari** [comment]
Respectfully bumping this issue, as both the "main" and "unpkg" key in package.json point to files named: "martini", which (as stated in the summary) don't exist, breaking redirection/inclusion:
- [broken jsdelivr](https://cdn.jsdelivr.net/npm/@mapbox/martini)
- [broken unpkg](https://unpkg.com/@mapbox/martini)

**Comment by mourner** [comment]
Apologies for the late response, just published v0.2.0 with the change. https://unpkg.com/@mapbox/martini@0.2.0/martini.min.js

**Comment by mootari** [comment]
Thank you!
